# Generated by Django 3.1.3 on 2022-01-11 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=32)),
                ('desc', models.CharField(help_text='项目描述', max_length=256)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('isActive', models.BooleanField(default=True, help_text='是否激活')),
                ('creator', models.ForeignKey(help_text='创建者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maintainer', models.ManyToManyField(blank=True, help_text='维护者/成员', related_name='ProductMaintainer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='环境名称', max_length=32)),
                ('desc', models.CharField(help_text='环境描述', max_length=256)),
                ('address', models.CharField(help_text='环境地址', max_length=64)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('isActive', models.BooleanField(default=True, help_text='是否激活')),
                ('FK_pro', models.ForeignKey(help_text='关联项目', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('creator', models.ForeignKey(help_text='创建者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'env_pro',
            },
        ),
    ]
